### ISSUE TITLE
CONFIG is not a valid JSON

### ISSUE THREAD

**Issue by anhducbkhn** [meilisearch/docs-scraper#117]
This is my config.json file 

```
    {
  "index_uid": "gsxd",
  "start_urls": ["http://my_domain.vn/"],
  "sitemap_urls": ["http://my_domain.vn/sitemap.xml"],
  "stop_urls": [],
  "selectors": {
    "lvl0": {
      "selector": ".theme-default-content h1",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": {
      "selector": ".theme-default-content h2",
      "global": true,
      "default_value": "Chapter"
    },
    "text": ".theme-default-content p, .theme-default-content li"
  }
}
```

then I run docker

```
docker run -t --rm \
    -e MEILISEARCH_HOST_URL=http://my_domain.vn:7700 \
    -e MEILISEARCH_API_KEY=key \
    -v config.json:/docs-scraper/config.json \
    getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```

this is what I got 

```
Traceback (most recent call last):
  File "/docs-scraper/scraper/src/config/config_loader.py", line 99, in _load_config
    data = json.loads(config, object_pairs_hook=OrderedDict)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./docs_scraper", line 22, in <module>
    run_config(sys.argv[1])
  File "/docs-scraper/scraper/src/index.py", line 34, in run_config
    config = ConfigLoader(config)
  File "/docs-scraper/scraper/src/config/config_loader.py", line 67, in __init__
    data = self._load_config(config)
  File "/docs-scraper/scraper/src/config/config_loader.py", line 104, in _load_config
    raise ValueError('CONFIG is not a valid JSON') from value_error
ValueError: CONFIG is not a valid JSON
```

Please help!.

**Comment by bidoubiwa** [comment]
I tried it locally and it seems to be a correct JSON. But when I tried it  locally with an empty json and I got the same error you have!  It might come from your docker command. Are you sure the file is correctly communicated to docker?

```bash
Traceback (most recent call last):
  File "./docs_scraper", line 22, in <module>
    run_config(sys.argv[1])
  File "MeiliSearch/docs-scraper/scraper/src/index.py", line 34, in run_config
    config = ConfigLoader(config)
  File "MeiliSearch/docs-scraper/scraper/src/config/config_loader.py", line 67, in __init__
    data = self._load_config(config)
  File "MeiliSearch/docs-scraper/scraper/src/config/config_loader.py", line 104, in _load_config
    raise ValueError('CONFIG is not a valid JSON') from value_error
ValueError: CONFIG is not a valid JSON
```

**Comment by anhducbkhn** [comment]
@bidoubiwa did you try with docker?

My env:

```
Ubuntu: 20.4.2
Docker version 20.10.5, build 55c4c88
```

I created a folder, checked config file.

```
anhducbkhn@anhducbkhn-ThinkPad-T14:~/projects/docs-scraper$ ls -la 
total 12
drwxrwxr-x  2 anhducbkhn anhducbkhn 4096 Thg 4   3 08:02 .
drwxrwxr-x 14 anhducbkhn anhducbkhn 4096 Thg 4   3 07:51 ..
-rw-rw-r--  1 anhducbkhn anhducbkhn  479 Thg 4   3 07:51 config.json
```

then, I run docker command from terminal, 
```
docker run -t --rm     -e MEILISEARCH_HOST_URL="http://gxd.vn:7700"     -e MEILISEARCH_API_KEY=f08441dcf70dc8e361d804a80939e1fc11dc532a5eff2447fdfce07c50a04106     -v config.json:/docs-scraper/config.json     getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```
then, I got that error.

**Comment by bidoubiwa** [comment]
The error you have is when the json file is empty. So either 
```
:~/projects/docs-scraper$ ls -la 
```
```
-v config.json:/docs-scraper/config.json
```

the path is not correct. 

Or! 

```
anhducbkhn@anhducbkhn-ThinkPad-T14:~/projects/docs-scraper$ cat config.json
```

The file is empty.

I tried your docker line: 
```
$ docker run -t --rm     -e MEILISEARCH_HOST_URL="http://gxd.vn:7700"     -e MEILISEARCH_API_KEY=f08441dcf70dc8e361d804a80939e1fc11dc532a5eff2447fdfce07c50a04106     -v config.json:/docs-scraper/config.json     getmeili/docs-scraper:latest cat config.json

cat: config.json: Is a directory
```
```bash
$ docker run -t --rm     -e MEILISEARCH_HOST_URL="http://gxd.vn:7700"     -e MEILISEARCH_API_KEY=f08441dcf70dc8e361d804a80939e1fc11dc532a5eff2447fdfce07c50a04106     -v config.json:/docs-scraper/config.json     getmeili/docs-scraper:latest cat docs-scraper/config.json

cat: docs-scraper/config.json: No such file or directory
```

I think there must be something wrong with your docker command

**Comment by anhducbkhn** [comment]
@bidoubiwa so, the document https://github.com/meilisearch/docs-scraper/blob/main/README.md#with-docker- is not correct.

What I fix now is: 

Create a Dockerfile 
```
FROM getmeili/docs-scraper:latest

COPY config.json /docs-scraper/config.json
```
Then I build it 

```
sudo docker build -t anhduc.bkhn/docs-scraper:local . 
```
```
sudo docker run -t --rm     -e MEILISEARCH_HOST_URL=http://my_domain.vn:7700     -e MEILISEARCH_API_KEY=key     anhduc.bkhn/docs-scraper:local pipenv run ./docs_scraper config.json
```

The result
```
> Docs-Scraper: https://domain.vn/ 0 records)
> Docs-Scraper: https://domain.vn/404.html 0 records)
> Docs-Scraper: https://domain.vn/legal/luat-xay-dung-50-ghep-62.html 2058 records)
> Docs-Scraper: https://domain.vn/guide/ 13 records)
> Docs-Scraper: https://domain.vn/case/hoi-dap-thuong-gap.html 1 records)
> Docs-Scraper: https://domain.vn/case/tinh-huong-hoi-dap.html 1 records)
> Docs-Scraper: https://domain.vn/legal/co-so-phap-ly.html 48 records)
> Docs-Scraper: https://domain.vn/legal/ 1 records)
> Docs-Scraper: https://domain.vn/guide/lien-he.html 6 records)
> Docs-Scraper: https://domain.vn/guide/he-sinh-thai.html 23 records)
> Docs-Scraper: https://domain.vn/guide/huong-dan-su-dung.html 193 records)
> Docs-Scraper: https://domain.vn/legal/nghi-dinh-06-2021-qlcl.html 1263 records)

```

**Comment by bidoubiwa** [comment]
Thanks a lot, @anhducbkhn for pointing this out. I'll check this out and change the doc accordingly :)

**Comment by bidoubiwa** [comment]
@anhducbkhn I found the confusion!

It comes from this line in the readme: 

> `<absolute-path-to-your-config-file>` should be the absolute path of your configuration file defined at the previous step.

I tried the provided command again but with the absolute path to the file: 
```bash
docker run -t --rm \
    -e MEILISEARCH_HOST_URL=http://my_domain.vn:7700 \
    -e MEILISEARCH_API_KEY=key \
    -v /Users/me/MeiliSearch/docs-scraper/config.json:/docs-scraper/config.json \
    getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```

And it worked! 
Could you confirm this works for you as well?
