### ISSUE TITLE
docs scraper failed to build indexes with v0.28.0 405 Client Error: Method Not Allowed for url

### ISSUE THREAD

**Issue by theowenyoung** [meilisearch/docs-scraper#231]
**Description**
Description of what the bug is about.
[0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0)

**Current behavior**
```bash
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 101, in __validate
    request.raise_for_status()
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://meilisearch.owenyoung.com/indexes/owen-blog/settings
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./docs_scraper", line 22, in <module>
    run_config(sys.argv[1])
  File "/docs-scraper/scraper/src/index.py", line 40, in run_config
    meilisearch_helper = MeiliSearchHelper(
  File "/docs-scraper/scraper/src/meilisearch_helper.py", line 105, in __init__
    self.add_settings(MeiliSearchHelper.SETTINGS, custom_settings)
  File "/docs-scraper/scraper/src/meilisearch_helper.py", line 109, in add_settings
    self.meilisearch_index.update_settings(settings)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/meilisearch/index.py", line 641, in update_settings
    return self.http.post(
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 63, in post
    return self.send_request(requests.post, path, body, content_type)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 45, in send_request
    return self.__validate(request)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 104, in __validate
    raise MeiliSearchApiError(str(err), request) from err
meilisearch.errors.MeiliSearchApiError: MeiliSearchApiError. 405 Client Error: Method Not Allowed for url: https://meilisearch.owenyoung.com/indexes/owen-blog/settings
Error: Process completed with exit code 1.

```

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux] Debian
- Meilisearch version: [e.g. v.0.28.0]
- docs-scraper version: [e.g v0.12.2]

**Comment by theowenyoung** [comment]
I tried to redeploy 0.27.2, and it works. so it may be a problem to adapt of version 0.28.2

**Comment by brunoocasali** [comment]
Hi @theowenyoung, you're correct this package does not support Meilisearch v0.28 yet, you can check that here https://github.com/meilisearch/docs-scraper#-compatibility-with-meilisearch

There is an ongoing PR to add this functionality https://github.com/meilisearch/docs-scraper/pull/223

@alallema I'll close this, but feel free to reopen if you want to :)
