### ISSUE TITLE
Invalid URL error when running scraper from docker

### ISSUE THREAD

**Issue by nbyloff** [meilisearch/docs-scraper#429]
**Description**
I am trying to use the docker image to crawl a site, but it's throwing an error because it tries to use the `index_uid` value as a URL.

**Expected behavior**
I except the scraper to crawl my site and save the results. My config is below, and it works fine outside docker. I should note I tested on Meilisearch v1.2.0 and 1.3.0 came out when I had a working model & ready to convert to Docker. 

(Same error happens when using scraper v0.12.11 so I'm not sure what's supposed to change in the config for Docker, if anything). I followed the [directions from here](https://www.meilisearch.com/docs/learn/cookbooks/search_bar_for_docs#configuration-file).

````
{
  "index_uid": "tkf",
  "start_urls": ["https://mydomain.test"],
  "sitemap_urls": ["https://mydomain.test/sitemap.xml"],
  "selectors": {
    "lvl0": {
      "selector": ".main h1"
    },
    "lvl1": ".main h2",
    "lvl2": ".main h3",
    "text": ".main p, .main li"
  }
}
```` 

Here is the relevant entry from my `docker-compose.yml` file:

````
  scraper:
    image: getmeili/docs-scraper:v0.12.12
    container_name: "tkf_scraper"
    profiles: ["search"]
    command: pipenv run ./docs_scraper config.json
    volumes:
      - ./config/scraper_config.json:/docs-scraper/config.json
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILISEARCH_HOST_URL: ${MEILISEARCH_HOST_URL}
      MEILISEARCH_API_KEY: ${MEILI_MASTER_KEY}
    networks:
      - backend
````

And I run it with this:
````
docker-compose run --rm scraper
````

**Current behavior**
I get the error below.  Essentially it's trying to use the index_uid value as a URL to crawl.

**Screenshots or Logs**
````
Traceback (most recent call last):
  File "/docs-scraper/./docs_scraper", line 22, in <module>
    run_config(sys.argv[1])
  File "/docs-scraper/scraper/src/index.py", line 40, in run_config
    meilisearch_helper = MeiliSearchHelper(
  File "/docs-scraper/scraper/src/meilisearch_helper.py", line 106, in __init__
    self.delete_index()
  File "/docs-scraper/scraper/src/meilisearch_helper.py", line 114, in delete_index
    self.meilisearch_index.delete()
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/meilisearch/index.py", line 68, in delete
    task = self.http.delete(f"{self.config.paths.index}/{self.uid}")
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 96, in delete
    return self.send_request(requests.delete, path, body)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 51, in send_request
    request = http_method(
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/api.py", line 157, in delete
    return request("delete", url, **kwargs)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/root/.local/share/virtualenvs/docs-scraper-PNgpf51m/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'search/indexes/tkf': No scheme supplied. Perhaps you meant https://search/indexes/tkf?
ERROR: 1
````

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Meilisearch version: v1.3.0
- docs-scraper version: v0.12.12

**Comment by sanders41** [comment]
Try to update your volume to use the full path to the config file and see if you still have issues. I’m not sure why, but I have seen this resolve issues with the scraper in docker. 

```yml
/home/some_path/config/scraper_config.json:/docs-scraper/config.json
```

**Comment by nbyloff** [comment]
@sanders41 Just tried it; same result. When I look at the source code, it does look like it's passing the `index_uid` to the http.delete method. And it seems to be reading the config file fine.
